# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openv < Formula
  desc "OpenV is a CLI tool to manage environment variables in 1Password"
  homepage ""
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/HINTERLAND-software/openv/releases/download/v0.2.1/openv_Darwin_x86_64.tar.gz"
      sha256 "20e8888a777ccfac6fdaef7279c9d3f6a7001d9e83b99b63a3bbaaf6ccf73bda"

      def install
        bin.install "openv"
      end
    end
    on_arm do
      url "https://github.com/HINTERLAND-software/openv/releases/download/v0.2.1/openv_Darwin_arm64.tar.gz"
      sha256 "6c008667bcf3f9c8976a9c1cad20d6aefdc0ca0b3d0ea331392d4b9ff17b9984"

      def install
        bin.install "openv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HINTERLAND-software/openv/releases/download/v0.2.1/openv_Linux_x86_64.tar.gz"
        sha256 "77f22a2a2be4a3643991a95bafb895ff4b34e975f635579994e5eaaaa7c9ce08"

        def install
          bin.install "openv"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HINTERLAND-software/openv/releases/download/v0.2.1/openv_Linux_arm64.tar.gz"
        sha256 "98562a0f86880a6c4687e4bcaa925fe6028db8a0b23e008f2671dfe7bd6017f0"

        def install
          bin.install "openv"
        end
      end
    end
  end

  test do
    system "#{bin}/openv version"
  end
end
