# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openv < Formula
  desc "OpenV is a CLI tool to manage environment variables in 1Password"
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/HINTERLAND-software/openv/releases/download/v0.1.0/openv_Darwin_x86_64.tar.gz"
      sha256 "a319b4cdb85bd5b36e5ca0eb003342df88460cef2ea299dca2d70ee82b77cbc9"

      def install
        bin.install "openv"
      end
    end
    on_arm do
      url "https://github.com/HINTERLAND-software/openv/releases/download/v0.1.0/openv_Darwin_arm64.tar.gz"
      sha256 "cba32a6d62796b5c14e70de1d9e17b2ced553f4c9212e619d123be7d57b07f8e"

      def install
        bin.install "openv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HINTERLAND-software/openv/releases/download/v0.1.0/openv_Linux_x86_64.tar.gz"
        sha256 "71e4275c6233653775cadc6a6004d6cf24febf66b9ae8d47acdec7ff325c8a1a"

        def install
          bin.install "openv"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HINTERLAND-software/openv/releases/download/v0.1.0/openv_Linux_arm64.tar.gz"
        sha256 "9ace6c7b967bf2da5f1bebea1ff23c65d9dfeef92e3733812bd89f969d0e89f9"

        def install
          bin.install "openv"
        end
      end
    end
  end

  test do
    system "#{bin}/openv version"
  end
end
